### ISSUE TITLE
Possible to enable emojis?

### ISSUE THREAD

**Issue by dalelowry** [elightup/falcon#4]
I love Falcon but users like to leave emojis in comments and I want them to be able to do so. Is there a way I can alter the plugin to allow emojis? (I'm not a developer, only know html and some CSS and PHP.)

**Comment by rilwis** [comment]
Hi @dalelowry , thanks for your feedback. We will make a settings page for the plugin where you can enable/disable each option.

**Comment by rilwis** [comment]
The settings page is now available under Settings > Falcon in version 2.0.1. Please update.
