### ISSUE TITLE
"The plugin does not have a valid header."

### ISSUE THREAD

**Issue by sisaacrussell** [elightup/falcon#7]
> "The plugin does not have a valid header."

Upon initial activation from WP.org directory search after install, this error is shown. URL: https://www.example.com/wp-admin/plugins.php?_wpnonce=ec76e529a2&action=activate&plugin=falcon/src/Embed.php

Activating from the Installed Plugins page works properly. URL: https://www.example.com/wp-admin/plugins.php?action=activate&plugin=falcon%2Ffalcon.php&plugin_status=all&paged=1&s&_wpnonce=2ea47b9924

Tested on 2 different sites.

**Comment by rilwis** [comment]
Fixed that in version 2.0.1. Please update.
